from google import genai
from google.genai import types

from app.core.config import settings
from app.schemas.ai_analysis import AIAnalysisResult


client = genai.Client(
    api_key=settings.GEMINI_API_KEY
)

MODEL_NAME = "gemini-3.5-flash-lite"


def calculate_overall_score(
    ats_score: int,
    technical_score: int,
    project_score: int,
    content_score: int,
) -> int:
    overall_score = (
        ats_score * 0.30
        + technical_score * 0.30
        + project_score * 0.25
        + content_score * 0.15
    )

    return round(overall_score)


def analyze_resume_text(resume_text: str) -> AIAnalysisResult:
    prompt = f"""
You are an expert technical resume evaluator.

Analyze the resume provided below.

Your evaluation must be:

- factual
- consistent
- evidence-based
- conservative
- repeatable

IMPORTANT RULES:

1. Evaluate ONLY information explicitly present in the resume.
2. Never invent skills, experience, companies, projects, certifications,
   achievements, education, or technologies.
3. Do not assume that a skill exists just because another related skill exists.
4. Do not reward information that is not actually present.
5. Do not penalize the resume for information that cannot reasonably be
   determined from the provided text.
6. Use the same scoring standards every time you analyze a resume.
7. Avoid subjective score inflation.
8. Scores must reflect the actual evidence in the resume.

============================================================
SCORING RUBRIC
============================================================

ATS SCORE (0-100)

Evaluate:

- ATS compatibility
- keyword relevance
- section headings
- formatting
- readability
- machine parsability
- relevant technical terminology

90-100:
Excellent ATS structure, clear headings, strong keyword usage,
clean formatting, and strong machine parsability.

75-89:
Good ATS compatibility with some missing keywords or minor structural issues.

60-74:
Moderate ATS compatibility with noticeable keyword or formatting issues.

40-59:
Weak ATS compatibility with significant issues.

0-39:
Very poor ATS compatibility.

============================================================

TECHNICAL SCORE (0-100)

Evaluate:

- technical skill strength
- relevance of technologies
- technical depth
- evidence of technical skills
- technical skills demonstrated through projects or experience

90-100:
Strong technical depth, relevant technologies, multiple demonstrated
technical skills, and strong evidence through projects/experience.

75-89:
Good technical foundation with several relevant skills and evidence.

60-74:
Moderate technical skill coverage with limited evidence.

40-59:
Weak technical coverage.

0-39:
Very limited technical information.

============================================================

PROJECT SCORE (0-100)

Evaluate:

- project quality
- technical complexity
- technologies used
- functionality
- technical depth
- measurable impact
- clarity of project descriptions

90-100:
Strong projects with clear technologies, functionality, impact,
and measurable results.

75-89:
Good projects with relevant technologies and reasonable descriptions.

60-74:
Projects exist but lack depth, technical details, or measurable impact.

40-59:
Weak project descriptions or limited technical evidence.

0-39:
Few or no meaningful projects.

============================================================

CONTENT SCORE (0-100)

Evaluate the overall quality of the resume content, including:

- clarity
- completeness
- section quality
- bullet-point quality
- measurable achievements
- quality of descriptions
- relevance of information
- consistency of information
- effectiveness of resume content
- professional presentation of information

90-100:
Excellent content quality with clear, complete, specific, relevant,
and achievement-focused information.

75-89:
Good content quality with mostly clear and relevant information,
but some areas could be strengthened.

60-74:
Moderate content quality with noticeable gaps, generic descriptions,
or limited measurable evidence.

40-59:
Weak content quality with significant missing, unclear, or generic content.

0-39:
Very poor or highly incomplete resume content.

============================================================

OVERALL SCORE
============================================================

DO NOT calculate the final overall score yourself.

The backend will calculate the final overall score using:

ATS = 30%
Technical = 30%
Projects = 25%
Content = 15%

Formula:

Overall Score =
(ATS Score × 0.30)
+ (Technical Score × 0.30)
+ (Project Score × 0.25)
+ (Content Score × 0.15)

Return the four component scores accurately.

The backend will ignore any overall score generated by the model
and calculate the final overall score itself.

============================================================

EVALUATION AREAS
============================================================

Evaluate:

1. ATS compatibility
2. Technical skills
3. Projects
4. Resume content quality
5. Resume weaknesses
6. Missing relevant technical skills
7. Actionable recommendations

============================================================

STRENGTHS
============================================================

List only meaningful strengths supported by the resume.

Do not create generic strengths such as:

- "Good resume"
- "Strong candidate"
- "Well formatted"

unless the resume clearly provides evidence.

============================================================

WEAKNESSES
============================================================

List specific weaknesses supported by the resume.

Examples:

- Missing measurable project outcomes
- Weak project descriptions
- Missing technical keywords
- Inconsistent dates
- Poor section organization
- Missing links
- Lack of quantified achievements

Do not invent weaknesses that are not supported by the resume.

============================================================

MISSING SKILLS
============================================================

Identify relevant technical skills that appear to be missing based on
the technologies and role direction demonstrated in the resume.

Do not recommend unrelated technologies.

============================================================

RECOMMENDATIONS
============================================================

Provide practical and actionable recommendations.

Each recommendation should explain what should be improved.

Avoid vague recommendations such as:

"Improve your resume."

============================================================

AI FEEDBACK
============================================================

Provide detailed overall feedback explaining:

- strongest aspects
- biggest weaknesses
- ATS concerns
- technical strengths
- project quality
- content quality
- most important improvements

The feedback must be based only on the resume.

============================================================

CONSISTENCY REQUIREMENT
============================================================

When the exact same resume text is analyzed multiple times:

- use the same scoring criteria
- use the same evidence
- avoid unnecessary score changes
- do not change scores merely because wording differs
- keep scores within a narrow range unless the evidence supports a change

============================================================

RESUME
============================================================

--- BEGIN RESUME ---

{resume_text}

--- END RESUME ---
"""

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=AIAnalysisResult,

            # Reduce randomness for more consistent evaluations.
            temperature=0.2,

            # Keep a single candidate.
            candidate_count=1,

            # Fixed seed improves reproducibility for identical inputs.
            seed=42,

            # Prevent tool/function behavior during resume evaluation.
            automatic_function_calling=types.AutomaticFunctionCallingConfig(
                disable=True
            ),
        ),
    )

    if response.parsed is not None:
        result = response.parsed
    else:
        result = AIAnalysisResult.model_validate_json(
            response.text
        )

    # The backend is the single source of truth for the final score.
    result.overall_score = calculate_overall_score(
        ats_score=result.ats_score,
        technical_score=result.technical_score,
        project_score=result.project_score,
        content_score=result.content_score,
    )

    return result